# OAuth
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix:   /login

auth0_login:
    path: /auth0/callback

auth0_logout:
    path: /auth0/logout

# TODO _locale не повторятся
# Main routes
index:
    path: /{_locale}
    controller: App\Controller\HomeController::index
    requirements:
        _locale: en|ru
    defaults:
        _locale: en

blog:
    path: /blog/{page}
    controller: App\Controller\PostsController::allPosts
    requirements:
        page: '\d+'
    defaults:
        page: 1

post:
    path: /post/{id}/{slug}
    controller: App\Controller\PostsController::post
    requirements:
        slug: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        id:  '\d+'

post_create_comment:
    path: /post/{id}/{slug}/new-comment/
    controller: App\Controller\PostsController::createComment

search:
    path: /search
    controller: App\Controller\SearchController::postSearch

# Auth
profile:
    path: /profile
    controller: App\Controller\ProfileController::index

app_logout:
    path: /logout

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Other
routes:
    path: /routes/
    controller: App\Controller\BlogController::routes

#api_login_check:
#  path: /api/login_check
#
#register:
#  path: /api/register
#  controller: App\Controller\RESTful\Auth\AuthController::register
#  methods: POST
#
#res:
#  path: /api/res
#  controller: App\Controller\RESTful\Auth\AuthController::res
#
#api:
#  path: /api
#  controller: App\Controller\RESTful\Auth\AuthController::api
