#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path:     /
  controller: App\Controller\BlogController::index

routes:
  path:     /routes/
  controller: App\Controller\BlogController::routes

posts:
  path:     /posts/{page}
  controller: App\Controller\BlogController::posts
  requirements:
    page: '\d+'
  defaults:
    page: 1
